{{- $image := .Values.image | default dict }}
{{- $app := .Values.app | default dict }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "phoenix-app.fullname" . }}
  labels:
    app: {{ template "phoenix-app.name" . }}
    chart: {{ template "phoenix-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "phoenix-app.name" . }}
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "phoenix-app.name" . }}
        release: {{ .Release.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ $image.repository }}:{{ $image.tag }}"
          imagePullPolicy: {{ $image.pullPolicy }}
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: APP_HOST
              value: "{{ $app.host }}"
            - name: APP_PORT
              value: "{{ $app.port }}"
            - name: DATABASE_URL
              value: "{{ $app.dbUrl }}"
            - name: AUTH0_DOMAIN
              value: "{{ $app.auth0Domain }}"
            - name: AUTH0_CLIENT_ID
              value: "{{ $app.auth0ClientId }}"
            - name: AUTH0_CLIENT_SECRET
              value: "{{ $app.auth0ClientSecret }}"
            - name: SECRET_KEY_BASE
              value: "{{ $app.secretKeyBase }}"
            - name: DM_EMAIL_FROM
              value: "{{ $app.dmEmailFrom }}"
            - name: DM_SEEDER_QA_ENABLED
              value: "{{ $app.dmSeederQAEnabled }}"
            - name: DM_SEEDER_MINIMAL_ENABLED
              value: "{{ $app.dmSeederMinimalEnabled }}"
            - name: DM_ROOT_ENABLED
              value: "{{ $app.dmRootEnabled }}"
            - name: DM_RX_CODE_BASE_LENGTH
              value: "{{ $app.dmRxCodeBaseLength }}"
            - name: SMTP_HOSTNAME
              value: "{{ $app.smtpHostname }}"
            - name: SMTP_USERNAME
              value: "{{ $app.smtpUsername }}"
            - name: SMTP_PASSWORD
              value: "{{ $app.smtpPassword }}"
            - name: GOOGLE_MAPS_API_KEY
              value: "{{ $app.googleMapsApiKey }}"

          ports:
            - containerPort: {{ $app.port }}
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /status
              port: {{ $app.port }}
            initialDelaySeconds: 40
          readinessProbe:
            httpGet:
              path: /status
              port: {{ $app.port }}
            initialDelaySeconds: 20
          resources:
{{ toYaml .Values.resources | indent 12 }}
    {{- with .Values.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
