{{- $ingress := .Values.ingress | default dict }}
{{- if $ingress.enabled -}}
{{- $fullName := include "phoenix-app.fullname" . -}}
{{- $servicePort := .Values.service.port -}}
{{- $ingressPath := $ingress.path -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ $fullName }}
  labels:
    app: {{ template "phoenix-app.name" . }}
    chart: {{ template "phoenix-app.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with $ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if $ingress.tls }}
  tls:
  {{- range $ingress.tls }}
    - hosts:
      - "{{ .Release.Namespace }}.testing.scripts.vet"
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
    - host: "{{ .Release.Namespace }}.testing.scripts.vet"
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
{{- end }}
