apiVersion: v2
appVersion: 0.4.0
description: A generic Helm chart for deploying Elixir 1.9+ releases of Phoenix applicaitons to Kubernetes
name: phoenix-app
version: 0.4.0
engine: gotpl
dependencies:
  - name: common
    repository: https://charts.bitnami.com/bitnami
    tags:
      - bitnami-common
    version: 1.x.x
